### ISSUE TITLE
While migrating angular 2 rc4 to angular 6 I am facing this err : Error: Cannot find module 'webpack/lib/removeAndDo'  Please help me out

### ISSUE THREAD

**Issue by Nisha-Yadav-1** [Nisha-Yadav-1/Angular6#1]
Error: Cannot find module 'webpack/lib/removeAndDo'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)

**Comment by rousan** [comment]
??

**Comment by PankajMSharma** [comment]
First option is to ->
Uninstall global webpack using:-
`npm u -g webpack`
Install following in devDependencies:-
`npm install --save-dev webpack webpack-cli html-webpack-plugin webpack-dev-server webpack-dev-middleware`
Install `webpack-dev-server` and `webpack-dev-middleware` as per your requirement. `webpack-cli` is necessary as per webpack 4.
OR
other option is ->
to link the global webpack to local webpack by following command:-
`npm i webpack -g; npm link webpack --save-dev`
